In [1]:
import pandas as pd 
import numpy as np
from tabulate import tabulate
data = pd.read_csv("./outputs/env_prmt_82.csv")

In [2]:
data.head(5)

,Model,Step,Time,Cost,Prob,Results
0,0,1,1037787613,50/50/50/51/50/,0.2007797022609135/0.2007797022609135/0.200779...,0/1/2/3/4/
1,0,2,1113380335,50/50/50/50/50/,0.19999999999999998/0.19999999999999998/0.1999...,0/1/2/3/4/
2,0,3,1113376947,53/52/50/50/50/,0.19224981312111578/0.196056616940785/0.203897...,0/1/2/3/4/
3,0,4,821576148,54/54/50/50/50/,0.19066622558816398/0.19066622558816398/0.2062...,0/1/2/3/4/
4,0,5,718839775,50/50/50/50/50/,0.19999999999999998/0.19999999999999998/0.1999...,0/1/2/3/4/

In [14]:
row_10 = data[0::5]
row_30 = data[1::5]
row_50 = data[2::5]
row_70 = data[3::5]
row_100 = data[4::5]

In [15]:
def precision(stringList, answer):
    goal_count = 0
    found = 0
    for result in stringList:
        if result == str(answer):
            found = 1
        goal_count += 1
    return found/(goal_count-1)

def recall(stringList, answer):
    found = 0
    for result in stringList:
        if result == str(answer):
            found = 1
            break
    return found

def accuracy(total, stringList, answer):
    tp = 0
    tn = 0
    fp = 0
    fn = 0
    for result in stringList[0:-1]:
        if result == str(answer):
            tp += 1
        else:
            fp += 1
    
    fn = 1 - tp
    
    # total is the number of all goals
    tn = total - tp - fp - fn
    return (tp + tn)/(tn + tp + fp + fn)

def func_precision(stringList, answer):
    goal_count = 0
    found = 0
    for result in stringList:
        if result == str(answer):
            found = 1
        goal_count += 1
    return found/(goal_count-1)

def func_recall(stringList, answer):
    found = 0
    for result in stringList:
        if result == str(answer):
            found = 1
            break
    return found

def func_accuracy(total, stringList, answer):
    tp = 0
    tn = 0
    fp = 0
    fn = 0
    for result in stringList[0:-1]:
        if result == str(answer):
            tp += 1
        else:
            fp += 1
    
    fn = 1 - tp
    
    # total is the number of all goals
    tn = total - tp - fp - fn
    return (tp + tn)/(tn + tp + fp + fn)

In [18]:
def calculate_statistics(rows):
    length = rows.shape[0]
    
    precision = 0
    recall = 0
    accuracy = 0
        
    for index, row in rows.iterrows():
        
        answer = row["Model"]
        results = row["Results"].split("/")
        all_candidates = row["Cost"].split("/")
        
        total = len(all_candidates)-1   # the last one is /
        
        
        
        p = func_precision(results, answer)
        r = func_recall(results, answer)
        a = func_accuracy(total, results, answer)
        
        precision += p
        recall += r
        accuracy += a
        
    precision = precision/length
    recall = recall/length
    accuracy = accuracy/length 
    
    return precision, recall, accuracy

In [33]:
matrix = []
matrix.append(calculate_statistics(row_10))
matrix.append(calculate_statistics(row_30))
matrix.append(calculate_statistics(row_50))
matrix.append(calculate_statistics(row_70))
matrix.append(calculate_statistics(row_100))

matrix

[(0.22466666666666718, 0.96, 0.25900000000000084),
 (0.3670000000000004, 0.775, 0.571),
 (0.41400000000000015, 0.72, 0.6269999999999999),
 (0.4969166666666667, 0.755, 0.7069999999999997),
 (0.575833333333333, 0.875, 0.7349999999999999)]

In [34]:
table = tabulate(matrix, headers=["p", "r", "a"])
print(table)

       p      r      a
--------  -----  -----
0.224667  0.96   0.259
0.367     0.775  0.571
0.414     0.72   0.627
0.496917  0.755  0.707
0.575833  0.875  0.735

In [35]:
row_100

,Model,Step,Time,Cost,Prob,Results
4,0,5,718839775,50/50/50/50/50/,0.19999999999999998/0.19999999999999998/0.1999...,0/1/2/3/4/
9,0,44,8634017509,50/470/61/105/127/,0.42241588937472796/1.1199469565054391E-4/0.34...,0/2/
14,0,40,8617760349,65/366/70/136/116/,0.3649251523032088/0.003815555294694451/0.3383...,0/2/
19,0,44,7290389564,50/446/50/57/50/,0.2582529613503241/1.0961661629503074E-4/0.258...,0/2/3/4/
24,0,19,3585715182,76/205/82/90/67/,0.24869469079646508/0.03730648526493871/0.2276...,0/2/4/
...,...,...,...,...,...,...
979,4,42,11938653359,97/526/118/99/100/,0.2652995563698378/0.0033311199492696538/0.214...,0/2/3/4/
984,4,44,13071188599,148/475/171/171/67/,0.17466751350094628/0.0014248416924293275/0.12...,4/
989,4,44,10772944048,129/516/128/133/50/,0.13068945807506022/6.617772624826812E-5/0.133...,4/
994,4,44,6975746736,50/436/59/59/50/,0.27196355464229005/1.404421829790126E-4/0.227...,0/2/3/4/
999,4,44,6996518380,50/435/50/55/50/,0.25594168783365695/1.3478559190293674E-4/0.25...,0/2/3/4/